qkd_sources:
  - qkd_source_id: "source1"
    type: "qix"
    num_subscribers: 1
    metrics:
      bin_size: 10
      update_period:
        value: 5
        unit: seconds
    serial:
      device: "/dev/pts/3"
      baud: 9600
      data_bits: 8
      flow_control: none
      stop_bits: one
sessions:
  - id: "session1"
    levels: "iwecfm"
    link_layer:
      enabled: true
      address:
        local: 10
        remote: 1
    security:
      mode: "initiator"	  
      session:
        max_payload_size: 4096                             # maximum size of a sent or received message payload
        ttl_pad:                                           # how much pad to apply to session messages for time validity
          value: 10
          unit: seconds
        max_nonce_value: 32768                             # maximum value for a session nonce
        nonce_renegotiation_trigger_value: 32700           # nonce count when the initiator starts trying to renegotiate
        max_session_duration:                              # maximum validity time for an established session
          value: 1
          unit: hours
        session_time_renegotiation_trigger:                # session time when the initiator starts trying to renegotiate
          value: 59
          unit: minutes
      handshake:
        response_timeout:
          value: 2
          unit: seconds
        retry_timeout:
          value: 5
          unit: seconds
        type: "qkd"
        key_source_id: "source1"
        subscriber_id: 0
        max_key_cache_size: 100
    transport:
      type: "tcp"
      max_sessions: 1
      listen:
        address: "127.0.0.1"
        port: 20000
      connect:
        address: "127.0.0.1"
        port: 20001
