qkd_sources:
  - qkd_source_id: "source1"
    type: "qix"
    num_subscribers: 1
    serial:
      device: "/dev/pts/5"
      baud: 9600
      data_bits: 8
      flow_control: none
      stop_bits: one
sessions:
  - id: "session1"
    levels: "iwemf"
    link_layer:
      enabled: true
      address:
        local: 10
        remote: 1
    security:
      mode: "responder"	  
      session:
        max_payload_size: 4096
        ttl_pad:
          value: 10
          unit: seconds
      handshake:
        type: "qkd"
        key_source_id: "source1"
        subscriber_id: 0
        max_key_cache_size: 100
    transport:
      type: "tcp"
      max_sessions: 1
      listen:
        address: "127.0.0.1"
        port: 20000
      connect:
        address: "127.0.0.1"
        port: 20001
